#!/bin/sh
module="mbspipe"
device="mbspipe0"

# invoke rmmod with all arguments we got
/sbin/rmmod $module
# Remove stale nodes
rm -f /dev/${device}
#ls -l /dev | grep pexor
echo MBSPIPE module unloaded.