#!/bin/sh
# N.Kurz, EE, GSI, 4-Sep2-13: modified for diefferent kernel versions
# JAM, EE, GSI, 29-Oct-2013: provided different devicenames for kinpex, pexaria
#            usage "load kinpex"

KV=`uname -r`
module="pexor_$KV"
class="pexor"
device="pexor"
#device="kinpex"
if [ $# -gt 0 ];then
  device=$1
  shift
fi
mode="664"
echo "module: $module.ko"
/sbin/insmod ./$module.ko
chmod a+rw /dev/${device}0
ln -sf ${device}0 /dev/${class}
ls -l /dev/*pex*

