#!/bin/sh
module="pexor"
device="pexor"
mode="664"

# Group: since distributions do it differently, look for wheel or use staff
#if grep -q '^staff:' /etc/group; then
#    group="staff"
#else
#    group="wheel"
#fi

/sbin/insmod ./$module.ko

# retrieve major number
#major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
#echo "PEXOR Major: $major"

#rm -f /dev/${device}0
#mknod /dev/${device}0 c $major 0
chmod a+rw /dev/${device}0
ln -sf ${device}0 /dev/${device}
ls -l /dev/pexor*
