#!/bin/sh
module="mbspex"
pexorname="pexor"    
kinpexname="kinpex"
# invoke rmmod with all arguments we got
/sbin/rmmod $module
# Remove stale nodes
rm -f /dev/${pexorname}
rm -f /dev/${pexorname}0
rm -f /dev/${kinpexname}
rm -f /dev/${kinpexname}0
#ls -l /dev | grep pexor
echo module ${module} unloaded.