#!/bin/sh
# JAM EE, GSI, 5-Nov-2021: loader for mbsmem driver; adopted from pexor driver with kernel version in name

KV=`uname -r`
module="mbsmem_$KV"
class="mbsmem"
device="mebsmem0"
if [ $# -gt 0 ];then
  device=$1
  shift
fi
pexorname="mbsmem"    
#mode="664"
echo "Installing module: $module.ko"
/sbin/insmod ./$module.ko
echo "sleep before we check device nodes..."
sleep 3 
# now look what we got
if  [ -e "/dev/${device}" ]
	then
	echo "MBSMEM LOAD: use device name from command line /dev/${device}" 	
elif [ -e "/dev/${pexorname}0" ]
	then
	device=${pexorname}0
else
 	echo "MBSMEM LOAD: could not find device of pexor family at /dev Exiting!"
 	exit
fi
echo "found device /dev/${device}"
chmod a+rw /dev/${device}
ln -sf /dev/${device} /dev/${class}
ls -l /dev/*mbsmem*

