#!/bin/sh
module="vetar"
modulex="vetar"
device="vetar"


/sbin/insmod ./$module.ko

# retrieve major number
major=$(awk "\$2==\"$modulex\" {print \$1}" /proc/devices)
echo "${device} Major: $major"

rm -f /dev/${device}0
mknod /dev/${device}0 c $major 0
chmod a+rw /dev/${device}0
ln -sf ${device}0 /dev/${device}
ls -l /dev/${device}*
